//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBM_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDiseaseRelation
    {
        public int ID { get; set; }
        public int PatientID { get; set; }
        public int DiseaseID { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public Nullable<int> PrescriptionID { get; set; }
        public System.DateTime ChangedOn { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Disease Disease { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
